<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dated_news"
 *
 * Auto generated by Extension Builder 2017-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'Recurr',
    'description'      => 'Provides the Recurr Library https://github.com/simshaun/recurr for Extbase Extensions',
    'category'         => 'be',
    'author'           => 'Falk Röder',
    'author_email'     => 'mail@falk-roeder.de',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 1,
    'version'          => '1.0.0',
    'constraints'      => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' =>
        array(
            'classmap' => array('Vendor')
        ),
];
